name: Super Smash Bros
main: net.supersmashcraft.SSCPlugin
description: Super Smash Plugin
author: Ultimate
version: 0.0.1-dev
website: http://supersmashcraft.net

commands:
   ssc:
      description: The main Super Smash Craft command
      usage: /<command> [args]