name: Super Smash Bros
main: net.supersmashcraft.SSCPlugin
description: Super Smash Plugin
author: Ultimate
version: 0.0.2(dev)-b${BUILD_NUMBER}
website: http://supersmashcraft.net

commands:
   ssc:
      description: The main Super Smash Craft command
      usage: /<command> [args]
